language: generic
os: linux
dist: xenial

git:
  depth: 1

addons:
  apt:
    update: true
    packages:
      - pdf2htmlex

cache:
  directories:
    - "/tmp/texlive"
    - "$HOME/.texlive"

before_install:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  # Configure texlive profile
  - touch texlive.profile
  - |
    echo "selected_scheme scheme-full" >> texlive.profile
    echo "TEXDIR /tmp/texlive" >> texlive.profile
    echo "TEXMFCONFIG ~/.texlive/texmf-config" >> texlive.profile
    echo "TEXMFHOME ~/texmf" >> texlive.profile
    echo "TEXMFLOCAL /tmp/texlive/texmf-local" >> texlive.profile
    echo "TEXMFSYSCONFIG /tmp/texlive/texmf-config" >> texlive.profile
    echo "TEXMFSYSVAR /tmp/texlive/texmf-var" >> texlive.profile
    echo "TEXMFVAR ~/.texlive/texmf-var" >> texlive.profile
    echo "option_doc 0" >> texlive.profile
    echo "option_src 0" >> texlive.profile
  # Install up-to-date texlive
  - |
    if ! command -v pdflatex > /dev/null; then
      echo "Texlive not installed"
      echo "Downloading texlive and installing"
      wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
      tar -xzf install-tl-unx.tar.gz
      yes I | sudo ./install-tl-*/install-tl --profile=./texlive.profile
      echo "Finished install TexLive"
    fi
    echo "Updating TexLive"
    tlmgr option -- autobackup 0
    tlmgr update --self --all --no-auto-install
    echo "Finished updating TexLive"

script:
  - latexmk --version
  - lualatex --version
  - pdf2htmlEX --version
  - make all
